In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('IMDBdataset.csv')
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
sample = 'basic there a famili where a littl boy jake think there a zombi in hi closet hi parent are fight all the timethi movi is slower than a soap opera and suddenli jake decid to becom rambo and kill the zombieok first of all when your go to make a film you must decid if it a thriller or a drama as a drama the movi is watchabl parent are divorc argu like in real life and then we have jake with hi closet which total ruin all the film i expect to see a boogeyman similar movi and instead i watch a drama with some meaningless thriller spots3 out of 10 just for the well play parent descent dialog as for the shot with jake just ignor them'

In [8]:
sample_df = df[:100]
sample_df

review sentiment
0   One of the other reviewers has mentioned that ...  positive
1   A wonderful little production. <br /><br />The...  positive
2   I thought this was a wonderful way to spend ti...  positive
3   Basically there's a family where a little boy ...  negative
4   Petter Mattei's "Love in the Time of Money" is...  positive
..                                                ...       ...
95  Daniel Day-Lewis is the most versatile actor a...  positive
96  My guess would be this was originally going to...  negative
97  Well, I like to watch bad horror B-Movies, cau...  negative
98  This IS the worst movie I have ever seen, as w...  negative
99  I have been a Mario fan for as long as I can r...  positive

[100 rows x 2 columns]

In [6]:
## Bag of words (ngrams = 1)
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()


In [10]:
bow = cv.fit_transform(sample_df['review'])

In [11]:
cv.vocabulary_

{'one': 2924,
 'of': 2898,
 'the': 4189,
 'other': 2953,
 'reviewers': 3501,
 'has': 1882,
 'mentioned': 2623,
 'that': 4186,
 'after': 134,
 'watching': 4578,
 'just': 2268,
 'oz': 2984,
 'episode': 1384,
 'you': 4736,
 'll': 2456,
 'be': 402,
 'hooked': 1989,
 'they': 4205,
 'are': 271,
 'right': 3520,
 'as': 297,
 'this': 4215,
 'is': 2199,
 'exactly': 1421,
 'what': 4611,
 'happened': 1867,
 'with': 4657,
 'me': 2592,
 'br': 545,
 'first': 1576,
 'thing': 4208,
 'struck': 4013,
 'about': 59,
 'was': 4570,
 'its': 2210,
 'brutality': 588,
 'and': 218,
 'unflinching': 4411,
 'scenes': 3629,
 'violence': 4518,
 'which': 4621,
 'set': 3704,
 'in': 2089,
 'from': 1662,
 'word': 4679,
 'go': 1755,
 'trust': 4355,
 'not': 2856,
 'show': 3757,
 'for': 1618,
 'faint': 1487,
 'hearted': 1907,
 'or': 2939,
 'timid': 4254,
 'pulls': 3273,
 'no': 2835,
 'punches': 3276,
 'regards': 3398,
 'to': 4262,
 'drugs': 1255,
 'sex': 3711,
 'hardcore': 1874,
 'classic': 768,
 'use': 4460,
 'it': 2206,
 '

In [12]:
bow[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [14]:
cv.transform(['my review is not that good']).toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

### For bag of n-grams just use CountVectorizer(ngrams=(1...n,n))

## TFIDF (term frequency inverse document frequency)

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer()
tfidf = tf.fit_transform(sample_df['review'])
print(cv.transform(['my review is not that good']).toarray())

[[0 0 0 ... 0 0 0]]


In [20]:
tf.idf_

array([4.92197334, 4.92197334, 2.57059808, ..., 4.92197334, 4.92197334,
       4.92197334])